// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xogxuhptbuvccrdytwsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvZ3h1aHB0YnV2Y2NyZHl0d3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjkxMDEsImV4cCI6MjA3MjgwNTEwMX0.2FTgm4wwaBfYA2gxrk-UVTiWa_xfacN5T6UsA8zpfmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});